### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by YipSzeho** [ayanamiblhx/nonebot_plugin_youthstudy#5]
[ERROR] nonebot | Failed to import "nonebot_plugin_youthstudy"
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Program Files\Python39\lib\site-packages\nb_cli\handlers\deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\Administrator\CirnoBot\.\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "C:\Users\Administrator\CirnoBot\.\cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\load.py", line 30, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\manager.py", line 92, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Program Files\Python39\lib\site-packages\nonebot\plugin\manager.py", line 181, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Program Files\Python39\lib\site-packages\nonebot_plugin_youthstudy\__init__.py", line 12, in <module>
    async def _(bot: Bot, event: Event, state: T_State):
  File "C:\Program Files\Python39\lib\site-packages\nonebot\matcher.py", line 403, in _decorator
    cls.append_handler(func, parameterless=parameterless)
  File "C:\Program Files\Python39\lib\site-packages\nonebot\matcher.py", line 380, in append_handler
    handler_ = Dependent[Any].parse(
  File "C:\Program Files\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 130, in parse
    field_info = dependent.parse_param(param_name, param)
  File "C:\Program Files\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 86, in parse_param
    raise ValueError(
ValueError: Unknown parameter state for function <function _ at 0x00000228A30C4D30> with type typing.Dict[typing.Any, typing.Any]

**Comment by ayanamiblhx** [comment]
请更新至最新版nonebot2
